### ISSUE TITLE
add --workspace flag

### ISSUE THREAD

**Issue by kyrregjerstad** [Armadillidiid/pnpm-monorepo-demo#1]
Hi,

I recently came across [your article](https://blog.emmanuelisenah.com/setting-up-a-monorepo-using-pnpm-workspaces-with-typescript-and-tailwind) while learning about setting up a pnpm monorepo. Thanks for creating such a great resource!

While following along, I encountered an issue where pnpm would try to fetch local packages from npm instead of the workspace. I found that using the `--workspace` flag resolved this:

```bash
pnpm add appName --workspace @monorepo/packageName
```

Without this flag, pnpm would attempt to find the package on npm, leading to errors. I thought this might be a useful addition to your article, in case others run into the same issue.

Thanks again for the excellent guide!

**Comment by Armadillidiid** [comment]
Thank you so much. I've updated the article to reflect the fix.

**Comment by PaperPrototype** [comment]
"@monorepo/ui is not in the npm registry, or you have no permission to fetch it."

If you are getting the above error in this part of the tutorial:

<img width="2070" height="1152" alt="Image" src="https://github.com/user-attachments/assets/f3c400a9-a9bf-4c72-a241-03100f95737f" />

This is the correct command (for that example):
```sh
pnpm -w frontend add @monorepo/ui --workspace
```
